# Generated by Django 6.0.2 on 2026-02-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choices_text',
            new_name='choice_text',
        ),
    ]
